services:
  - type: web
    name: hebclass
    runtime: node
    buildCommand: cd frontend && npm install --include=dev && npm run build && cd ../backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
